spring:
  datasource:
    url: jdbc:postgresql://postgres-sql-api-trabalho:5432/pecas_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        mode: always

  server:
    port: 8088